language: python
python: "3.8"
cache: pip
services:
  - docker
before_install:
  - |
    docker pull amazonlinux:2018.03
    docker build -t transcriber:$TRAVIS_BUILD_ID .
before_script:
  - pip3 install awscli
script:
  # https://github.com/kibaffo33/aws_transcribe_to_docx
  # Build lambda function into zip file
  - docker run -v $(pwd):/var/app -it amazonlinux:2018.03 "chmod +x build.sh && ./build.sh"
  - chmod +x deploy.sh && ./deploy.sh

notifications:
  email: false