language: python
python: "3.8"
script:
  # https://github.com/kibaffo33/aws_transcribe_to_docx
  # Build lambda function into zip file
  - chmod +x build.sh
  - ./build.sh
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master

notifications:
  email: false