AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  S3Bucket: 
    Type: String
    Default: transcribe-everything-placed-here
    Description: S3 Bucket to place mp4 files into, and receive transcribed file into
Resources:
  CreateTranscription:
    DependsOn: LambdaExecutionRole
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |       
          from __future__ import print_function

          import boto3
          import datetime
          import time

          def handler(event, context):
            transcribe = boto3.client('transcribe')

            x = datetime.datetime.now()

            job_name = "Transcribe-Video-" + x.strftime("%Y-%m-%d-%H-%M-%S")
            job_uri = "s3://transcribe-everything-placed-here/empty.mp4"

            transcribe.start_transcription_job(
                TranscriptionJobName=job_name,
                Media={'MediaFileUri': job_uri},
                MediaFormat='mp4',
                LanguageCode='en-US'
            )

            while True:
                status = transcribe.get_transcription_job(TranscriptionJobName=job_name)
                if status['TranscriptionJob']['TranscriptionJobStatus'] in ['COMPLETED', 'FAILED']:
                    break
                print("Transcribing...")
                time.sleep(5)
            print(status)
            return "Complete"
      Handler: index.handler
      MemorySize: 1536
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Runtime: python3.7
      Timeout: 60

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: logs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
      - PolicyName: transcribe
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - transcribe:StartTranscriptionJob
            Resource: 
              - '*'

  LambdaInvokePermission:
    DependsOn: CreateTranscription
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt CreateTranscription.Arn
      Action: 'lambda:InvokeFunction'
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Sub 'arn:aws:s3:::${S3Bucket}'

  SrcBucket:
    DependsOn: CreateTranscription
    Type: AWS::S3::Bucket
    # NotificationConfiguration must be commented on stack creation,
    # then uncommented and deployed as an update.
    # See: https://aws.amazon.com/premiumsupport/knowledge-center/unable-validate-destination-s3/
    Properties:
      BucketName: transcribe-everything-placed-here
      #NotificationConfiguration:
      #  LambdaConfigurations:
      #    - Event: 's3:ObjectCreated:*'
      #      Filter:
      #        S3Key:
      #          Rules:
      #            -
      #              Name: suffix
      #              Value: mp4
      #      Function: !GetAtt CreateTranscription.Arn