AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CreateTranscription:
    DependsOn: LambdaExecutionRole
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: !Sub
          print 1;
      Handler: handler
      MemorySize: 1536
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Runtime: nodejs10.x
      Timeout: 60

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*

  LambdaInvokePermission:
    DependsOn: CreateTranscription
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt CreateTranscription.Arn
      Action: 'lambda:InvokeFunction'
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Sub 'arn:aws:s3:::${SrcBucket}'

  SrcBucket:
    DependsOn: CreateTranscription
    Type: AWS::S3::Bucket
    # NotificationConfiguration must be commented on stack creation,
    # then uncommented and deployed as an update.
    # See: https://aws.amazon.com/premiumsupport/knowledge-center/unable-validate-destination-s3/
    Properties:
      BucketName: transcribe-everything-placed-here
      #NotificationConfiguration:
      #  LambdaConfigurations:
      #    - Event: 's3:ObjectCreated:*'
      #      Filter:
      #        S3Key:
      #          Rules:
      #            -
      #              Name: suffix
      #              Value: mp4
      #      Function: !GetAtt CreateTranscription.Arn